language:
- cpp

os:
- linux

compiler:
- g++

before_install:
- sudo apt-get install -y valgrind

script:
- make
- export PATH=$PWD/bin:$PATH
- echo $PATH
- git clone https://github.com/frederic-mahe/swarm-tests.git
- cd swarm-tests
- source run_all_tests.sh
- valgrind swarm -o /dev/null <(printf ">a_1\nA\n")
