language: c++

os: linux

dist: bionic

compiler: gcc

before_install:
- sudo apt-get install -y valgrind

script:
- make COVERAGE=1
- export PATH=$PWD/bin:$PATH
- git clone https://github.com/frederic-mahe/swarm-tests.git && cd swarm-tests && bash ./run_all_tests.sh | tee tests.log && ! grep -q FAIL tests.log
- cd ../src ; gcov *.cc

after_success:
- cd ~/swarm ; bash <(curl -s https://codecov.io/bash) -v
