language:
- cpp

os:
- linux

compiler:
- g++

before_install:
- sudo apt-get install -y valgrind

script:
- make
- export PATH=$PATH:$PWD/bin
- echo $PATH
- git clone https://github.com/frederic-mahe/swarm-tests.git
- source swarm-tests/run_all_tests.sh
