/*
    SWARM

    Copyright (C) 2012-2026 Torbjorn Rognes and Frederic Mahe

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Contact: Torbjorn Rognes <torognes@ifi.uio.no>,
    Department of Informatics, University of Oslo,
    PO Box 1080 Blindern, NO-0316 Oslo, Norway
*/

#include "../db.h"  // brings in zobrist.h transitively, plus the Sequence definition
#include "pseudo_rng.h"
#include <algorithm> // std::for_each
#include <cassert>
#include <cstddef>  // std::ptrdiff_t
#include <cstdint>  // uint64_t
#include <iterator>  // std::next
#include <vector>

#ifndef NDEBUG
// C++17 refactoring: [[maybe_unused]]
#include <limits>
#endif


// anonymous namespace: limit visibility and usage to this translation unit
namespace {

  auto to_uchar(char const nucleotide) -> unsigned char {
    // note: compressed nucleotides are in the range [-127, +127]
    return static_cast<unsigned char>(nucleotide);
  }


  auto fill_rng_table(std::vector<uint64_t> & tab_base_v,
                      unsigned int const zobrist_len) -> void
  {
    /*
      Generate 4n random 64-bit numbers. They will represent the four
      different bases in any position (1 to n) of a sequence.  They will
      be XOR'ed together to form the hash of that sequence.  The number
      n, here 'zobrist_len', should be the length of the longest
      sequence to be hashed including potential additional insertions.

      The number is generated by xor'ing together four shifted
      31-bit random numbers.
    */
    static constexpr auto multiplier = 16U;

    /* allocate base table and fill with random 64 bit numbers */
    tab_base_v.resize(4ULL * zobrist_len);

    std::for_each(tab_base_v.begin(),
                  tab_base_v.end(),
                  [](uint64_t & rng_value) -> void {
                    // refactoring: comment states 31-bit random numbers?!
                    rng_value = rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                  });
  }


  auto fill_rng_byte_table(std::vector<uint64_t> const & tab_base_v,
                           std::vector<uint64_t> & tab_byte_base_v,
                           unsigned int const zobrist_len) -> void
  {
    static constexpr auto byte_range = 256U;

    /* allocate byte table and combine into bytes for faster computations */
    tab_byte_base_v.resize(1ULL * byte_range * (zobrist_len / 4));

    for(auto i = 0U; i < zobrist_len / 4; ++i) {
      for(auto j = 0U; j < byte_range; ++j) {
        auto rng_value = 0ULL;
        auto offset = j;
        // rng value stored at: 4 *  position   +  offset & 3U (= 0, 1, 2, or 3)
        rng_value ^= tab_base_v[(4 * ((4 * i) + 0)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 1)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 2)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 3)) + (offset & 3U)];
        tab_byte_base_v[(byte_range * i) + j] = rng_value;
      }
    }
  }

}  // end of anonymous namespace


// ----- class Zobrist -----

Zobrist::Zobrist(unsigned int const n)
{
  fill_rng_table(tab_base_v_, n);
  fill_rng_byte_table(tab_base_v_, tab_byte_base_v_, n);
}


auto Zobrist::value(unsigned int const pos, unsigned char const offset) const -> uint64_t
{
  assert(not tab_base_v_.empty());
  assert(offset == 0 or offset == 1 or offset == 2 or offset == 3);
  return tab_base_v_[(4 * pos) + offset];
}


auto Zobrist::hash(char const * seq, unsigned int const len) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq of length len. */
  /* len is the actual number of bases in the sequence */
  /* it is encoded in (len + 3 ) / 4 bytes */

  // refactoring: equivalent to a std::reduce() algorithm?
  static constexpr auto offset = 64U;
  static constexpr auto nt_per_byte = 4U;
  static constexpr auto bytes_per_uint64 = 8U;
  static constexpr auto nt_per_uint64 = nt_per_byte * bytes_per_uint64;  // 32 nt per uint64 chunk
  uint64_t zobrist_hash = 0;
  auto pos = 0U;

  // Bulk: 32 nt (8 bytes) per outer iteration. The fixed-trip-count
  // inner for-loop gives the compiler a clear hint to unroll.
  auto const n_chunks = len / nt_per_uint64;
  for (auto chunk = 0U; chunk < n_chunks; ++chunk)
    {
      for (auto byte_i = 0U; byte_i < bytes_per_uint64; ++byte_i)
        {
          auto const a_byte = to_uchar(*seq);
          auto const target_hash = (offset * pos) + a_byte;
          zobrist_hash ^= tab_byte_base_v_[target_hash];
          seq = std::next(seq);
          pos += nt_per_byte;
        }
    }

  // Tail handler: 0..31 nt left. First the remaining complete bytes
  // (0..7 of them), then the sub-byte residue (0..3 nt).
  while (pos + nt_per_byte <= len)
    {
      auto const a_byte = to_uchar(*seq);
      auto const target_hash = (offset * pos) + a_byte;
      zobrist_hash ^= tab_byte_base_v_[target_hash];
      seq = std::next(seq);
      pos += nt_per_byte;
    }

  if (pos < len)  // less than a byte remaining (hash pairs of bits one-by-one)
    {
      auto last_byte = to_uchar(*seq);
      seq = std::next(seq);  // useless in normal conditions, keep it for now
      while (pos < len)
        {
          zobrist_hash ^= value(pos, last_byte & 3U);
          last_byte >>= 2U;
          ++pos;
        }
    }

  return zobrist_hash;
}


// refactoring: unrolling does not work (hard to deal with the last positions (sub-byte)
// refactoring: factorize hash_delete_first() and hash_insert_first()?
auto Zobrist::hash_delete_first(char const * seq, unsigned int const len) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq,
     but delete the first base */

  static constexpr auto nt_per_byte = 4U;  // 4 nucleotides per byte
  static constexpr auto divider = 2U;
  auto offset = to_uchar(*seq);
  uint64_t zobrist_hash = 0;
  for(auto pos = 1U; pos < len; ++pos)
    {
      auto const is_new_byte = (pos & (nt_per_byte - 1)) == 0;
      if (is_new_byte) {  // every 4 positions, except the first one
        auto const target_chunk = (pos >> divider);
        assert(target_chunk <= std::numeric_limits<std::ptrdiff_t>::max());
        auto const target_chunk_signed = static_cast<std::ptrdiff_t>(target_chunk);
        offset = to_uchar(*std::next(seq, target_chunk_signed));  // load new data every 4 positions
      }
      else {
        offset >>= 2U;
      }
      zobrist_hash ^= value(pos - 1, offset & 3U);
    }
  return zobrist_hash;
}


auto Zobrist::hash_insert_first(char const * seq, unsigned int const len) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq,
     but insert a gap (no value) before the first base */

  static constexpr auto nt_per_byte = 4U;  // 4 nucleotides per byte
  static constexpr auto divider = 2U;
  auto offset = to_uchar(*seq);
  uint64_t zobrist_hash = 0;
  for(auto pos = 0U; pos < len; ++pos)
    {
      auto const is_new_byte = (pos & (nt_per_byte - 1)) == 0;
      if (is_new_byte) {  // every 4 positions, except the first one
        auto const target_chunk = (pos >> divider);
        assert(target_chunk <= std::numeric_limits<std::ptrdiff_t>::max());
        auto const target_chunk_signed = static_cast<std::ptrdiff_t>(target_chunk);
        offset = to_uchar(*std::next(seq, target_chunk_signed));  // load new data every 4 positions
      }
      else {
        offset >>= 2U;
      }
      zobrist_hash ^= value(pos + 1, offset & 3U);
    }
  return zobrist_hash;
}


auto Zobrist::hash(Sequence const & seq) const -> uint64_t
{
  return hash(seq.encoded.data(), seq.length);
}


auto Zobrist::hash_delete_first(Sequence const & seq) const -> uint64_t
{
  return hash_delete_first(seq.encoded.data(), seq.length);
}


auto Zobrist::hash_insert_first(Sequence const & seq) const -> uint64_t
{
  return hash_insert_first(seq.encoded.data(), seq.length);
}

