/*
    SWARM

    Copyright (C) 2012-2026 Torbjorn Rognes and Frederic Mahe

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Contact: Torbjorn Rognes <torognes@ifi.uio.no>,
    Department of Informatics, University of Oslo,
    PO Box 1080 Blindern, NO-0316 Oslo, Norway
*/

#include "../db.h"  // brings in zobrist.h transitively, plus the Sequence definition
#include "pseudo_rng.h"
#include <algorithm> // std::for_each
#include <cassert>
#include <cstdint>  // uint64_t
#include <iterator>  // std::next
#include <vector>


// anonymous namespace: limit visibility and usage to this translation unit
namespace {

  auto to_uchar(char const nucleotide) -> unsigned char {
    // note: compressed nucleotides are in the range [-127, +127]
    return static_cast<unsigned char>(nucleotide);
  }


  auto fill_rng_table(std::vector<uint64_t> & tab_base_v,
                      unsigned int const zobrist_len) -> void
  {
    /*
      Generate 4n random 64-bit numbers. They will represent the four
      different bases in any position (1 to n) of a sequence.  They will
      be XOR'ed together to form the hash of that sequence.  The number
      n, here 'zobrist_len', should be the length of the longest
      sequence to be hashed including potential additional insertions.

      The number is generated by xor'ing together four shifted
      31-bit random numbers.
    */
    static constexpr auto multiplier = 16U;

    /* allocate base table and fill with random 64 bit numbers */
    tab_base_v.resize(4ULL * zobrist_len);

    std::for_each(tab_base_v.begin(),
                  tab_base_v.end(),
                  [](uint64_t & rng_value) -> void {
                    // refactoring: comment states 31-bit random numbers?!
                    rng_value = rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                  });
  }


  auto fill_rng_byte_table(std::vector<uint64_t> const & tab_base_v,
                           std::vector<uint64_t> & tab_byte_base_v,
                           unsigned int const zobrist_len) -> void
  {
    static constexpr auto byte_range = 256U;

    /* allocate byte table and combine into bytes for faster computations */
    tab_byte_base_v.resize(1ULL * byte_range * (zobrist_len / 4));

    for(auto i = 0U; i < zobrist_len / 4; ++i) {
      for(auto j = 0U; j < byte_range; ++j) {
        auto rng_value = 0ULL;
        auto offset = j;
        // rng value stored at: 4 *  position   +  offset & 3U (= 0, 1, 2, or 3)
        rng_value ^= tab_base_v[(4 * ((4 * i) + 0)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 1)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 2)) + (offset & 3U)];
        offset >>= 2U;
        rng_value ^= tab_base_v[(4 * ((4 * i) + 3)) + (offset & 3U)];
        tab_byte_base_v[(byte_range * i) + j] = rng_value;
      }
    }
  }

}  // end of anonymous namespace


// ----- class Zobrist -----

Zobrist::Zobrist(unsigned int const n)
{
  fill_rng_table(tab_base_v_, n);
  fill_rng_byte_table(tab_base_v_, tab_byte_base_v_, n);
}


auto Zobrist::value(unsigned int const pos, unsigned char const offset) const -> uint64_t
{
  assert(not tab_base_v_.empty());
  assert(offset == 0 or offset == 1 or offset == 2 or offset == 3);
  return tab_base_v_[(4 * pos) + offset];
}


auto Zobrist::hash(char const * seq, unsigned int const len) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq of length len. */
  /* len is the actual number of bases in the sequence */
  /* it is encoded in (len + 3 ) / 4 bytes */

  static constexpr auto byte_range = 256U;  // tab_byte_base_v_ entries per byte position
  static constexpr auto nt_per_byte = 4U;
  uint64_t zobrist_hash = 0;

  // Bulk: hash all complete bytes via the precomputed byte-rate
  // table. std::for_each over a View gives the compiler a tight,
  // contiguous-iterator loop with a simple lambda body — easier to
  // autovectorize than a moving-pointer hand-rolled loop.
  auto const n_complete_bytes = len / nt_per_byte;
  auto const bulk = View<char>{seq, n_complete_bytes};
  auto byte_idx = 0U;
  std::for_each(bulk.cbegin(), bulk.cend(),
                [&](char const byte) {
                  auto const a_byte = to_uchar(byte);
                  zobrist_hash ^= tab_byte_base_v_[(byte_range * byte_idx) + a_byte];
                  ++byte_idx;
                });

  // Sub-byte residue: 0..3 nt that didn't fill a byte
  auto pos = n_complete_bytes * nt_per_byte;
  if (pos < len)
    {
      auto last_byte = to_uchar(*std::next(seq, n_complete_bytes));
      while (pos < len)
        {
          zobrist_hash ^= value(pos, last_byte & 3U);
          last_byte >>= 2U;
          ++pos;
        }
    }

  return zobrist_hash;
}


// refactoring: unrolling does not work (hard to deal with the last positions (sub-byte)
auto Zobrist::hash_first_shifted(Sequence const & seq,
                                 First_base_op const op) const -> uint64_t
{
  /* Shared body of hash_delete_first and hash_insert_first.
     remove:     skip the first input base, output position = input pos - 1.
     insert_gap: keep all input bases,     output position = input pos + 1. */

  static constexpr auto nt_per_byte = 4U;  // 4 nucleotides per byte
  static constexpr auto divider = 2U;
  auto const len = seq.length;
  auto const n_bytes = (len + nt_per_byte - 1U) / nt_per_byte;
  auto const view = View<char>{seq.encoded.data(), n_bytes};
  auto const start = (op == First_base_op::remove) ? 1U : 0U;
  auto offset = to_uchar(view.front());
  uint64_t zobrist_hash = 0;
  for(auto pos = start; pos < len; ++pos)
    {
      auto const is_new_byte = (pos & (nt_per_byte - 1)) == 0;
      if (is_new_byte) {  // every 4 positions, except the first one
        offset = to_uchar(view[pos >> divider]);  // load new data every 4 positions
      }
      else {
        offset >>= 2U;
      }
      auto const out_pos = (op == First_base_op::remove) ? pos - 1U : pos + 1U;
      zobrist_hash ^= value(out_pos, offset & 3U);
    }
  return zobrist_hash;
}


auto Zobrist::hash(Sequence const & seq) const -> uint64_t
{
  return hash(seq.encoded.data(), seq.length);
}


auto Zobrist::hash_delete_first(Sequence const & seq) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq,
     but delete the first base */
  return hash_first_shifted(seq, First_base_op::remove);
}


auto Zobrist::hash_insert_first(Sequence const & seq) const -> uint64_t
{
  /* compute the Zobrist hash function of sequence seq,
     but insert a gap (no value) before the first base */
  return hash_first_shifted(seq, First_base_op::insert_gap);
}

