/*
    SWARM

    Copyright (C) 2012-2026 Torbjorn Rognes and Frederic Mahe

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Contact: Torbjorn Rognes <torognes@ifi.uio.no>,
    Department of Informatics, University of Oslo,
    PO Box 1080 Blindern, NO-0316 Oslo, Norway
*/

#include "../db.hpp"  // brings in zobrist.hpp transitively, plus the Sequence definition
#include "pseudo_rng.hpp"
#include "view.hpp"  // View<>
#include <algorithm> // std::for_each
#include <array>
#include <cassert>
#include <cstdint>  // uint64_t
#include <iterator>  // std::next
#include <numeric>  // std::accumulate
#include <vector>


// anonymous namespace: limit visibility and usage to this translation unit
namespace {

  auto to_uchar(char const nucleotide) -> unsigned char {
    // note: compressed nucleotides are in the range [-127, +127]
    return static_cast<unsigned char>(nucleotide);
  }

}  // end of anonymous namespace


// ----- class Zobrist -----

Zobrist::Zobrist(unsigned int const n) {
  fill_rng_table(n);
  fill_rng_byte_table(n);
}


auto Zobrist::fill_rng_table(unsigned int const zobrist_len) -> void {
  /*
    Generate 4n random 64-bit numbers. They will represent the four
    different bases in any position (1 to n) of a sequence.  They will
    be XOR'ed together to form the hash of that sequence.  The number
    n, here 'zobrist_len', should be the length of the longest
    sequence to be hashed including potential additional insertions.

    The 64-bit number is generated by xor'ing together four shifted
    64-bit random numbers.
  */
  static constexpr auto multiplier = 16U;
  using Row = std::array<uint64_t, nt_per_byte>;

  /* allocate base table and fill with random 64 bit numbers */
  tab_base_v_.resize(zobrist_len);

  std::for_each(tab_base_v_.begin(),
                tab_base_v_.end(),
                [](Row & row) -> void {
                  for (auto & rng_value : row) {
                    rng_value = rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                    rng_value <<= multiplier;
                    rng_value ^= rand_64();
                  }
                });
}


auto Zobrist::fill_rng_byte_table(unsigned int const zobrist_len) -> void {
  auto const n_byte_positions = zobrist_len / nt_per_byte;

  /* allocate byte table and combine into bytes for faster computations */
  tab_byte_base_v_.resize(n_byte_positions);

  for (auto i = 0U; i < n_byte_positions; ++i) {
    for (auto j = 0U; j < byte_range; ++j) {
      auto rng_value = 0ULL;
      auto offset = j;
      for (auto k = 0U; k < nt_per_byte; ++k) {
        rng_value ^= value((nt_per_byte * i) + k, offset & 3U);
        offset >>= 2U;
      }
      tab_byte_base_v_[i][j] = rng_value;
    }
  }
}


auto Zobrist::value(unsigned int const pos, unsigned char const offset) const -> uint64_t {
  assert(not tab_base_v_.empty());
  assert(offset == 0 or offset == 1 or offset == 2 or offset == 3);
  return tab_base_v_[pos][offset];
}


auto Zobrist::hash(Sequence const & seq) const -> uint64_t {
  /* compute the Zobrist hash function of sequence seq. */
  /* seq.length is the actual number of bases in the sequence */
  /* it is encoded in (seq.length + 3 ) / 4 bytes */

  auto const len = seq.length;
  uint64_t zobrist_hash = 0;

  // Bulk: hash all complete bytes via the precomputed byte-rate
  // table. std::for_each over a View gives the compiler a tight,
  // contiguous-iterator loop with a simple lambda body — easier to
  // autovectorize than a moving-pointer hand-rolled loop.
  auto const n_complete_bytes = len / nt_per_byte;
  auto const bulk = seq.encoded.first(n_complete_bytes);
  auto byte_idx = 0U;
  std::for_each(bulk.cbegin(), bulk.cend(),
                [&](char const byte) -> void {
                  auto const a_byte = to_uchar(byte);
                  zobrist_hash ^= tab_byte_base_v_[byte_idx][a_byte];
                  ++byte_idx;
                });

  // Sub-byte residue: 0..3 nt that didn't fill a byte
  auto pos = n_complete_bytes * nt_per_byte;
  if (pos < len) {
    auto last_byte = to_uchar(seq.encoded[n_complete_bytes]);
    while (pos < len) {
      zobrist_hash ^= value(pos, last_byte & 3U);
      last_byte >>= 2U;
      ++pos;
    }
  }

  return zobrist_hash;
}


auto Zobrist::hash_first_shifted(Sequence const & seq,
                                 First_base_op const operation) const -> uint64_t {
  /* Shared body of hash_delete_first and hash_insert_first.
     remove:     skip the first input base, output position = input pos - 1.
     insert_gap: keep all input bases,     output position = input pos + 1. */

  auto const len = seq.length;
  auto const n_bytes = (len + nt_per_byte - 1U) / nt_per_byte;
  auto const view = seq.encoded.first(n_bytes);
  auto const start = (operation == First_base_op::remove) ? 1U : 0U;

  auto byte_idx = 0U;
  return std::accumulate(view.cbegin(), view.cend(), uint64_t{0},
    [&](uint64_t acc, char const byte_value) -> uint64_t {
      auto offset = to_uchar(byte_value);
      auto const base_pos = nt_per_byte * byte_idx;
      ++byte_idx;
      for (auto k = 0U; k < nt_per_byte; ++k) {
        auto const pos = base_pos + k;
        if (pos >= start and pos < len) {
          auto const out_pos = (operation == First_base_op::remove) ? pos - 1U : pos + 1U;
          acc ^= value(out_pos, offset & 3U);
        }
        offset >>= 2U;
      }
      return acc;
    });
}


auto Zobrist::hash_delete_first(Sequence const & seq) const -> uint64_t {
  /* compute the Zobrist hash function of sequence seq,
     but delete the first base */
  return hash_first_shifted(seq, First_base_op::remove);
}


auto Zobrist::hash_insert_first(Sequence const & seq) const -> uint64_t {
  /* compute the Zobrist hash function of sequence seq,
     but insert a gap (no value) before the first base */
  return hash_first_shifted(seq, First_base_op::insert_gap);
}

