name: Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install make mingw-w64 g++-x86-64-linux-gnu g++-aarch64-linux-gnu g++-powerpc64le-linux-gnu

    - name: Build for Windows x86_64
      run: |
        make clean
        make CXX="x86_64-w64-mingw32-g++" RELEASE=1

    - name: Build for Linux aarch64
      run: |
        make clean
        make CXX="aarch64-linux-gnu-g++" RELEASE=1

    - name: Build for Linux powerpc64le
      run: |
        make clean
        make CXX="powerpc64le-linux-gnu-g++" RELEASE=1

    - name: Build for Linux x86_64
      run: |
        make clean
        make CXX="x86_64-linux-gnu-g++" RELEASE=1
        bin/swarm -v

    - name: Install and run tests, for Linux x86_64 only
      run: |
        sudo apt-get update
        sudo apt-get -y install valgrind
        export PATH=$PWD/bin:$PATH
        git clone --branch ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }} https://github.com/frederic-mahe/swarm-tests
        cd swarm-tests
        bash ./run_all_tests.sh


  macos-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build for macos aarch64
      run: |
        make clean
        make RELEASE=1
        bin/swarm -v

    - name: Install and run tests
      run: |
        export PATH=$PWD/bin:$PATH
        git clone --branch ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }} https://github.com/frederic-mahe/swarm-tests
        cd swarm-tests
        bash ./run_all_tests.sh


  macos-x86_64:
    runs-on: macos-15-intel

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build for macos x86_64
      run: |
        make clean
        make RELEASE=1
        bin/swarm -v

    - name: Install and run tests
      run: |
        export PATH=$PWD/bin:$PATH
        git clone --branch ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }} https://github.com/frederic-mahe/swarm-tests
        cd swarm-tests
        bash ./run_all_tests.sh


  freebsd-x86_64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build and test on FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        release: "14.2"
        usesh: true
        prepare: |
          pkg install -y gmake bash git
        run: |
          gmake clean
          gmake RELEASE=1
          bin/swarm -v
          export PATH=$PWD/bin:$PATH
          git clone --branch ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }} https://github.com/frederic-mahe/swarm-tests
          cd swarm-tests
          bash ./run_all_tests.sh
